'use client';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import type { Contract } from '@/types';

const styles = StyleSheet.create({
  page: { backgroundColor: '#ffffff', padding: 40, fontFamily: 'Helvetica', fontSize: 9, color: '#333' },
  header: { borderBottom: '2px solid #000', paddingBottom: 12, marginBottom: 20 },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#000', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#555' },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#000', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8, paddingBottom: 4, borderBottom: '1px solid #eee' },
  row: { flexDirection: 'row', marginBottom: 6 },
  label: { width: 120, fontSize: 8, color: '#888', fontFamily: 'Helvetica-Bold' },
  value: { flex: 1, fontSize: 9, color: '#333' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTop: '1px solid #eee', paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#aaa' },
});

function GigSheetDoc({ contract: c }: { contract: Contract }) {
  const gs = c.gigSheet;
  return (
    <Document title={`Gig Sheet — ${gs.eventName}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>GIG SHEET</Text>
          <Text style={styles.subtitle}>{gs.eventName} · EXPORTS Platform</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Performance Details</Text>
          {[
            ['Artist', gs.artistName],
            ['Event', gs.eventName],
            ['Date', gs.date],
            ['Venue', `${gs.venue}, ${gs.venueAddress}`],
            ['Set Time', gs.slotTime],
            ['Load-In', gs.loadInTime],
            ['Soundcheck', gs.soundcheckTime],
          ].map(([k, v]) => (
            <View style={styles.row} key={k}>
              <Text style={styles.label}>{k}</Text>
              <Text style={styles.value}>{v}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Payment</Text>
          {[
            ['Total Fee', `${gs.currency} $${gs.fee}`],
            ['Advance', `${gs.currency} $${gs.advanceAmount} — due ${gs.advanceDueDate}`],
            ['Balance', `${gs.currency} $${gs.fee - gs.advanceAmount} — on the night`],
          ].map(([k, v]) => (
            <View style={styles.row} key={k}>
              <Text style={styles.label}>{k}</Text>
              <Text style={styles.value}>{v}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Contacts</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Promoter</Text>
            <Text style={styles.value}>{gs.promoterContact}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Venue</Text>
            <Text style={styles.value}>{gs.venueContact}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Riders</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Technical</Text>
            <Text style={styles.value}>{gs.technicalRider}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Hospitality</Text>
            <Text style={styles.value}>{gs.hospitalityRider}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by EXPORTS · exports.nz</Text>
          <Text style={styles.footerText}>{gs.eventName} · {gs.date}</Text>
        </View>
      </Page>
    </Document>
  );
}

export default function GigSheetPDF({ contract }: { contract: Contract }) {
  return (
    <PDFDownloadLink
      document={<GigSheetDoc contract={contract} />}
      fileName={`gig-sheet-${contract.gigSheet.eventName.replace(/\s+/g, '-').toLowerCase()}.pdf`}
      className="inline-flex items-center gap-2 px-4 py-2 bg-[#1a1a1a] border border-[#252525] rounded-sm text-sm text-[#ededed] hover:border-[#3a3a3a] transition-colors"
    >
      {({ loading }) => loading ? 'Generating PDF...' : '⬇ Download Gig Sheet PDF'}
    </PDFDownloadLink>
  );
}
